export const SET_SHOW_BACKDROP = 'SET_SHOW_BACKDROP';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SET_CURRENT_RATE = 'SET_CURRENT_RATE';

export const SET_CURRENT_DELIVERY_METHODS = 'SET_CURRENT_DELIVERY_METHODS';

export const SET_REGISTER_INFORMATION = 'SET_REGISTER_INFORMATION';
export const SET_REGISTER_DRIVER_LICENCE_SELECTED =
  'SET_REGISTER_DRIVER_LICENCE_SELECTED';
export const SET_REGISTER_ENTER_ADDRESS_MANUALLY_SELECTED =
  'SET_REGISTER_ENTER_ADDRESS_MANUALLY_SELECTED';
